federation_version: 2
subgraphs:
  accounts:
    routing_url: http://localhost:4001/graphql
    schema:
      file: ../services/accounts/schema.graphql
  reviews:
    routing_url: http://localhost:4002/graphql
    schema:
      file: ../services/reviews/schema.graphql
  products:
    routing_url: http://localhost:4003/graphql
    schema:
      file: ../services/products/schema.graphql
  inventory:
    routing_url: http://localhost:4004/graphql
    schema:
      file: ../services/inventory/schema.graphql