kind: Security
name: apollo-gateway-fed-2-demo
label: dev
spec:
  profiles:
  - name: guest
    require_operation_name: true
    max_depth: 3
    max_height: 8
    max_aliases: 1
  - name: member
    require_operation_name: true
    max_depth: 3
    max_height: 10
    max_aliases: 2
  - name: employee
    require_operation_name: true
    max_depth: 5
    max_height: 16
    max_aliases: 3